<?php

use Faker\Provider\Uuid;
use Illuminate\Database\Seeder;

class CitySeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        $cities = array("Banda Aceh",
            "Langsa",
            "Lhokseumawe",
            "Meulaboh",
            "Sabang",
            "Subulussalam",
            "Denpasar",
            "Pangkalpinang",
            "Cilegon",
            "Serang",
            "Tangerang Selatan",
            "Tangerang",
            "Bengkulu",
            "Gorontalo",
            "Kota Administrasi Jakarta Barat",
            "Kota Administrasi Jakarta Pusat",
            "Kota Administrasi Jakarta Selatan",
            "Kota Administrasi Jakarta Timur",
            "Kota Administrasi Jakarta Utara",
            "Sungai Penuh",
            "Jambi",
            "Bandung",
            "Bekasi",
            "Bogor",
            "Cimahi",
            "Cirebon",
            "Depok",
            "Sukabumi",
            "Tasikmalaya",
            "Banjar",
            "Magelang",
            "Pekalongan",
            "Purwokerto",
            "Salatiga",
            "Semarang",
            "Surakarta",
            "Tegal",
            "Batu",
            "Blitar",
            "Kediri",
            "Madiun",
            "Malang",
            "Mojokerto",
            "Pasuruan",
            "Probolinggo",
            "Surabaya",
            "Pontianak",
            "Singkawang",
            "Banjarbaru",
            "Banjarmasin",
            "Palangkaraya",
            "Balikpapan",
            "Bontang",
            "Samarinda",
            "Tarakan",
            "Batam",
            "Tanjungpinang",
            "Bandar Lampung",
            "Metro",
            "Ternate",
            "Tidore Kepulauan",
            "Ambon",
            "Tual",
            "Bima",
            "Mataram",
            "Kupang",
            "Sorong",
            "Jayapura",
            "Dumai",
            "Pekanbaru",
            "Makassar",
            "Palopo",
            "Parepare",
            "Palu",
            "Bau-Bau",
            "Kendari",
            "Bitung",
            "Kotamobagu",
            "Manado",
            "Tomohon",
            "Bukittinggi",
            "Padang",
            "Padangpanjang",
            "Pariaman",
            "Payakumbuh",
            "Sawahlunto",
            "Solok",
            "Lubuklinggau",
            "Pagaralam",
            "Palembang",
            "Prabumulih",
            "Binjai",
            "Medan",
            "Padang Sidempuan",
            "Pematangsiantar",
            "Sibolga",
            "Tanjungbalai",
            "Tebingtinggi",
            "Yogyakarta");
        for($i = 0 ; $i < sizeof($cities) ; $i++){
            DB::table('cities')->insert([
                'id' => Uuid::uuid(),
                'name' =>$cities[$i]
            ]);
        }
    }
}
